### ISSUE TITLE
Failed to parse CMake console output to locate port start/end markers

### ISSUE THREAD

**Issue by esdandreu** [esdandreu/python-extension-cpp#2]
Failed `vcpkg install` when running `pip install .` on Windows 11 in powershell
```
-- Running vcpkg install
      Failed to parse CMake console output to locate port start/end markers
      -- Running vcpkg install - failed
      CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:816 (message):
        vcpkg install failed.  See logs for more information:
        C:\Users\esdan\Desktop\python-extension-cpp\_skbuild\win-amd64-3.8\cmake-build\vcpkg-manifest-install.log
      Call Stack (most recent call first):
        C:/Users/esdan/AppData/Local/Temp/pip-build-env-w7bbgfo8/overlay/Lib/site-packages/cmake/data/share/cmake-3.22/Modules/CMakeDetermineSystem.cmake:124 (include)
        CMakeLists.txt:35 (project)


      CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
        File "C:\Users\esdan\AppData\Local\Temp\pip-build-env-w7bbgfo8\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 588, in setup
          env = cmkr.configure(cmake_args,
        File "C:\Users\esdan\AppData\Local\Temp\pip-build-env-w7bbgfo8\overlay\Lib\site-packages\skbuild\cmaker.py", line 289, in configure
          raise SKBuildError(


      --------------------------------------------------------------------------------
      -- Trying "Ninja (Visual Studio 17 2022 x64 v143)" generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying "Ninja (Visual Studio 17 2022 x64 v143)" generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          C:\Users\esdan\Desktop\python-extension-cpp\_skbuild\win-amd64-3.8\cmake-build
        Command:
          cmake 'C:\Users\esdan\Desktop\python-extension-cpp' -G Ninja '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\esdan\Desktop\python-extension-cpp\_skbuild\win-amd64-3.8\cmake-install\src\python\pyproject' '-DPYTHON_EXECUTABLE:FILEPATH=c:\users\esdan\desktop\python-extension-cpp\venv\scripts\python.exe' -DPYTHON_VERSION_STRING:STRING=3.8.10 '-DPYTHON_INCLUDE_DIR:PATH=C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\Include' '-DPYTHON_LIBRARY:FILEPATH=C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\libs\python38.lib' -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\esdan\AppData\Local\Temp\pip-build-env-w7bbgfo8\overlay\Lib\site-packages\skbuild\resources\cmake' '-DCMAKE_MAKE_PROGRAM:FILEPATH=C:\Users\esdan\AppData\Local\Temp\pip-build-env-w7bbgfo8\overlay\Lib\site-packages\ninja\data\bin\ninja' '-DCMAKE_TOOLCHAIN_FILE:PATH=C:\Users\esdan\Desktop\python-extension-cpp\vcpkg\scripts\buildsystems\vcpkg.cmake' -DBUILD_PYTHON_API=ON -DBUILD_TESTS=OFF -DCMAKE_BUILD_TYPE:STRING=Release

      Traceback (most recent call last):

      An error occurred while configuring with CMake.
        Command:
          cmake 'C:\Users\esdan\Desktop\python-extension-cpp' -G Ninja '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\esdan\Desktop\python-extension-cpp\_skbuild\win-amd64-3.8\cmake-install\src\python\pyproject' '-DPYTHON_EXECUTABLE:FILEPATH=c:\users\esdan\desktop\python-extension-cpp\venv\scripts\python.exe' -DPYTHON_VERSION_STRING:STRING=3.8.10 '-DPYTHON_INCLUDE_DIR:PATH=C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\Include' '-DPYTHON_LIBRARY:FILEPATH=C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\libs\python38.lib' -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\esdan\AppData\Local\Temp\pip-build-env-w7bbgfo8\overlay\Lib\site-packages\skbuild\resources\cmake' '-DCMAKE_MAKE_PROGRAM:FILEPATH=C:\Users\esdan\AppData\Local\Temp\pip-build-env-w7bbgfo8\overlay\Lib\site-packages\ninja\data\bin\ninja' '-DCMAKE_TOOLCHAIN_FILE:PATH=C:\Users\esdan\Desktop\python-extension-cpp\vcpkg\scripts\buildsystems\vcpkg.cmake' -DBUILD_PYTHON_API=ON -DBUILD_TESTS=OFF -DCMAKE_BUILD_TYPE:STRING=Release
        Source directory:
          C:\Users\esdan\Desktop\python-extension-cpp
        Working directory:
          C:\Users\esdan\Desktop\python-extension-cpp\_skbuild\win-amd64-3.8\cmake-build
```
- When installing via `python setup.py install` it works
- When installing in Windows Subsystem for Linux Ubuntu 20.04 via `pip install .` it also works

**Comment by esdandreu** [comment]
Keeping `cmake` out of the project requirements in `pyproject.toml` seems to have solved the issue

**Comment by esdandreu** [comment]
Not sure if deleting the `vcpkg` cache (located in
`C:\Users\<user>\AppData\Local\vcpkg` on Windows and in `~/.cache/vcpkg` on
Linux), and reinstalled `cmake` helped
